// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: 'swap',
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Vertkal Pilates 360° - Transforme seu corpo em 21 dias",
  description: "App interativo de Pilates com cronograma de 21 dias, gamificação e sistema de progresso. Transforme seu corpo com treinos personalizados, conquistas e conteúdo VIP exclusivo.",
  keywords: "pilates, fitness, treino, 21 dias, transformação, gamificação, VIP, exercícios",
  authors: [{ name: "Vertkal Pilates 360°" }],
  creator: "Vertkal Pilates 360°",
  publisher: "Vertkal Pilates 360°",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://vertkal-pilates-360.vercel.app'),
  openGraph: {
    title: "Vertkal Pilates 360° - Transforme seu corpo em 21 dias",
    description: "App interativo de Pilates com cronograma de 21 dias, gamificação e sistema de progresso.",
    type: "website",
    locale: "pt_BR",
    siteName: "Vertkal Pilates 360°",
  },
  twitter: {
    card: "summary_large_image",
    title: "Vertkal Pilates 360° - Transforme seu corpo em 21 dias",
    description: "App interativo de Pilates com cronograma de 21 dias, gamificação e sistema de progresso.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'google-site-verification-code',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${poppins.variable}`}>
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon.svg" />
        <meta name="theme-color" content="#eca20c" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </head>
      <body
        className={`font-inter antialiased bg-black text-white min-h-screen`}
        style={{
          fontFamily: 'var(--font-inter), var(--font-poppins), system-ui, sans-serif'
        }}
      >
        {children}
      </body>
    </html>
  );
}